
############################
# General Config
############################

[general]
 #there are as many logs as devices configured and
 #logdir set the Directory path for each device individual log
 logdir = "./log"
 #NOTE: main process log is now sent to standar ouput
 # logLevel set de main process log level
 # valid values: panic,fatal,error,warn,info,debug
 logLevel = "warn"

 ############################
 # DataBase Config
 ############################

[database]
#type sets the sql backend
#valid values sqlite3,mysql
 type = "sqlite3"
# these parameters are only for mysql
# host = 127.0.0.1:3306
# user = "root"
# password = ""
# name sets the database name
 name = "snmpcollector"
#sqllogfile sets the name for a file in the log/ direcotry where sql backend will write all SQL transactions
#sqllogfile = "sql.log"
 # debug adds extra verbosity to the SQL log
 debug = false


############################
# Self Monitorig Config
############################
#config for sending self monitoring metrics to our default influx db
# Sent Measurements will be
# <prefix>.goroutines
# <prefix>.memory.allocated
# <prefix>.memory.mallocs
# <prefix>.memory.frees
# <prefix>.memory.gc.total_pause
# <prefix>.memory.heap
# <prefix>.memory.gc.pause_per_second
# <prefix>.memory.gc.pause_per_interval
# <prefix>.memory.gc.gc_per_second

[selfmon]
 #enable true/false enable/disable self monitoring
 enabled = true
 #send data Frequency
 freq = 60
 #prefix for measurement naming
 prefix = "gvm"
 #adds extra tags to the measurement sent
 extratags = [ "instance=snmpcollector01" ]

############################
# Embedded WebServer Config
############################

[http]
 port   = 8090
 adminuser = "adm1"
 adminpassword = "adm1pass"
